print("Nan dhan da diver uhh")
print("hello")
print("Elakkiya")
print("ram//")
print("hello")
print("Hi...")
print("mass moni")
print("Hi its Preethi")
print("Niketana")
print("Malli")
print("js")
print("elakkiya check")