print("Nan dhan da diver uhh")
print("hello")
print("monika")
print("hello")
print("Elakkiya")
print("ram//")
print("hello")
print("Hi...")
print("Preethi")

print("Niketana")
print("Preethi")
print("Niketana")
